### ISSUE TITLE
[Error] php 7.2 depricated, now 7.4 

### ISSUE THREAD

**Issue by Tom-Neverwinter** [reynico/raspberry-noaa#101]
**Describe the bug**

php 7.2 repo is not found as it is depricated. 

**Screenshots and/or logs**
If applicable, add screenshots to help explain your problem. Logs are always welcome as well

**Server information (please complete the following information):**
 - OS: [e.g. Raspbian] raspbian stretch 08/04/2019 [last release]
 - Python version [e.g. 3.7.3] latest
 - SDR device [e.g. RTL-SDR v3] rtl-sdr v3

**Additional context**

wget -q https://packages.sury.org/php/apt.gpg -O- | sudo apt-key add -
 echo "deb https://packages.sury.org/php/ stretch main" | sudo tee /etc/apt/sources.list.d/php7.list
 sudo apt-get update
 
 sudo apt-get install php7.2-cli php7.2-fpm \
 php7.2-opcache php7.2-curl php7.2-mbstring \
 php7.2-pgsql php7.2-zip php7.2-xml php7.2-gd

solves php7.2 issue

fails to solve: libgfortran5 dependany

**Comment by reynico** [comment]
Hi Tom!
Errrr, seems like stretch doesn't have the php stuff in its repository. I'm running my station and my qemu'ed testing machine on Buster,

```
php7.1-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
php7.2-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
php7.3-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
```

I'll add a switch on the code to add the php7 repo if on stretch.
