### ISSUE TITLE
[Error] Add additional enhancements to webinterface

### ISSUE THREAD

**Issue by Crosswalkersam** [reynico/raspberry-noaa#108]
Hello,

I just added two new enhancements "SEA" and "THERM" to receive.sh as discribed in #42.
When connecting to the Pi via SFTP I can download and see the images with the new enhancements, but they are not shown in the webinterface. How can I get them to show there?

**Comment by reynico** [comment]
Hi!

You'll need to add both SEA and THERM enhancements to line 59 in your `/var/www/wx/Model/Conn.php` file https://github.com/reynico/raspberry-noaa/blob/master/templates/webpanel/Model/Conn.php#L59

**Comment by Crosswalkersam** [comment]
That worked, Thanks!
