### ISSUE TITLE
Meteor M2 image quality under Win10 and Raspberry

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#110]
Why is it that Meteor M2 under win10 Sdrsharp, LRPT decoder and Medet64 gives a better image than a comparable recording under Raspberry? When I compare the images, the quality difference is quite big. If necessary, I can send two images as comparison material. I think this is such a shame because I think Reynico's software compilation is great.

**Comment by reynico** [comment]
Hi Tom
Please upload both pictures to compare! Haven't use Windows for a while, so I don't have real comparison data

**Comment by tomamdy** [comment]
First one  raspberry software, second one Sdrsharp, LRPT decoder and Medet64.
![meteor m2 raspberry](https://user-images.githubusercontent.com/67389269/104808439-9b07b400-57e6-11eb-9d47-a2771cbfed07.jpg)

second one Sdrsharp, LRPT decoder and Medet64

![meteor m2 sdrsharp](https://user-images.githubusercontent.com/67389269/104808444-9e9b3b00-57e6-11eb-9292-64412929997b.jpg)

**Comment by tomamdy** [comment]
May be this helps, this part is from pi:
Total:       1.767562
Processing:   1.763140
Correlation:  0.000000
Viterbi:      0.000000
ECC:          0.000000
Remainder:    0.004422
Packets:      425 / 425
Elapsed time: 00:00:49.248
convert: length and filesize do not match `/var/www/wx/images/METEOR-M220210118-085349-122.bmp' @ warning/bmp.c/ReadBMPImage/839.
INFO : Rectifying image to adjust aspect ratio
Opened 1568x424 image
Spawning process  1
Spawning process  2
Spawning process  3
Spawning process  4

**Comment by reynico** [comment]
Hi tom,
yeah that's a huge difference, please follow this issue where guys are testing different settings to improve the reception: https://github.com/reynico/raspberry-noaa/issues/114
