### ISSUE TITLE
reception problem

### ISSUE THREAD

**Issue by fabiomarigliano** [reynico/raspberry-noaa#111]
hi, I installed everything according to the guide, but when I receive the satellites, I find myself in black and white images, very different from the ones I see in your twitter account, do you have any idea why? I receive the ZA MCIR and MICIR precip images.
![2469430E-0A5C-41B5-BD3C-C279E0046F91](https://user-images.githubusercontent.com/46231794/104505932-f66a5400-55e4-11eb-8ad3-7acaa7ad5e33.jpeg)

**Comment by fabiomarigliano** [comment]
I still get black and white images, does anyone have a problem with me? Thanks

![Schermata 2021-01-15 alle 19 46 32](https://user-images.githubusercontent.com/46231794/104766172-6229f980-576a-11eb-95bf-53799182399d.png)

**Comment by reynico** [comment]
Hi Fabio!
Seems like the reception is a bit noisy over there.  WHat's your hardware setup and location?

**Comment by fabiomarigliano** [comment]
Hi, I use raspberry Pi3 and QFH antenna, before with the old script I received color images even if a little noisy now only in black and white. Since I put the new script I can no longer receive the images as before. I enclose an example
![ErJkgzvXIAIG4uw](https://user-images.githubusercontent.com/46231794/104772539-e2089180-5773-11eb-809e-b1600554d93d.jpg)

**Comment by fabiomarigliano** [comment]
My location Italy Europe

**Comment by fabiomarigliano** [comment]
Now they are all like the pictures

![EryYn48W4AM3Izb](https://user-images.githubusercontent.com/46231794/104772769-3f9cde00-5774-11eb-8fb7-412b0b85b50b.jpg)

**Comment by reynico** [comment]
Could you please post the contents of the following files?

- /home/pi/.noaa.conf
- /home/pi/.wxtoimgrc
- /home/pi/.predict/predict.qth
- /home/pi/raspberry-noaa/sun.py

**Comment by fabiomarigliano** [comment]
NOAA_HOME=/home/pi/raspberry-noaa
NOAA_OUTPUT=/var/www/wx
METEOR_OUTPUT=/var/www/wx/meteor
RAMFS_AUDIO=/var/ramfs
SAT_MIN_ELEV=30
METEOR_MIN_ELEV=30
SUN_MIN_ELEV=1
LOG_LEVEL=DEBUG
LAT=40.0113100
LON=-18.1623700
BIAS_TEE="-T"
DELETE_AUDIO="true"
FLIP_METEOR_IMG="true"
GAIN=70
SCHEDULE_ISS="false"

**Comment by fabiomarigliano** [comment]
#
# WXtoImg configuration file written by WXtoImg.
# "man wxtoimg" or wxtoimg.html for details.
# WXtoImg version 2.11.2 beta
#
#
Registration Name: Kevin Schuchmann
Registration Email: mail@mail.com
Registration Key: CGHZ-PP9G-EAJZ-AWKK-NDNX
Signal Type: APT
Expert Mode: false
Status Info Size: 0
Large Pixmap Support: false
Prompt on Exit: true
Decode in Record: true
Scroll in Record: true
Direction: northbound
Sample Rate: 11025.00
#Resurs Sample Rate: 11025.0
#Meteor3 Sample Rate: 11025.0
#Meteor2 Sample Rate: 11025.0
#SICH1M Sample Rate: 11025.0
#SICH Sample Rate: 11025.0
#Okean Sample Rate: 11025.0
#NOAA Sample Rate: 11025.0
#Meteosat Sample Rate: 11025.0
#GOES Sample Rate: 11025.0
#GMS Sample Rate: 11025.0
#MTSAT Sample Rate: 11025.0
Set Sample Rate: false
Sharpen: 0.6
JPEG Quality: 90
AVI Codec: RGB
AVI Transparent: true
AVI Quality: 85
AVI Scale: 0.5000
Max Frames: 16
Frame Rate: 1.000
Image Format: JPEG
Anaglyph Image Format: png
Composite Image Format: png
Messages: normal
Resync: disabled
Noise Filter: 0
Noise Threshold: 44
Crop: disabled
Contrast: var
Illumination Compensation: none
Gamma: 1.40
Despeckle: 2.00
No Signal Fill: true
Audio Directory: /home/pi/wxtoimg/audio
Image Directory: /home/pi/wxtoimg/raw
Save Directory: /home/pi/wxtoimg/images
Map Directory: /home/pi/wxtoimg/maps
Thumbnail Directory: /home/pi/wxtoimg/thumbnails
Template for Audio: false
Filename Info: UTC YYYYMMDDHHMM
Temperature Units: C
Distance Units: km
Enhancement: -
Auto Image Template: %s-%f-%e
Auto Image Enhancements: "-" "contrast -a" "contrast -b" "NO" "HVCT" "MSA" "MCIR"
Record Type: A
Record Name Format: %Y%m%d%H%M
BMPs for DA: false
Record Bits: 16
Record Level: 25
Record Delay: 60
Record Rate: 11025
Record Only Active: enabled
Record Elevation: 20
Record Above: 8
Record Disable Info: false
Record Add: -N
Record Device: 0
Record Modes: ARCID
Recording Forces Location: false
Antenna Type: unknown
Receiver Type: none
Receiver Port: /dev/ttyAMA0
Receiver Baud: 0
Rotor Type: none
Rotor Port: /dev/ttyAMA0
Rotor Baud: 0
Park Elevation: 90.0
Park Azimuth: 180.0
GPS Port: /dev/ttyAMA0
GPS Baud: 4800
GPS Use: false
GPS Set Clock: false
Pass List Hours: 168
Process Time: 300
Use Alternate Memory Model: false
Delete Audio After: 999
Delete Maps After: 999
Delete Raw Images After: 999
Delete Images After: 999
Flip Meteor 3: disabled
Map Build: enabled
Map Overlay: disabled
Map Population: 0
Map Antialias: true
Map Thick Lines: false
Map Land-Sea: enabled
Map Lakes: disabled
Map Rivers: disabled
Map Country Borders: disabled
Map State Borders: disabled
Map Ground Station: disabled
Map Grid: 10
Map Offset Northbound: 0
Map Offset Southbound: 0
Map Land Color: light-green
Map Lake Color: light-green
Map River Color: light-green
Map Country Border Color: yellow
Map State Border Color: yellow
Map Ground Station Color: yellow
Map City Color: orange
Map Grid Color: red
Ground Station: Casarano, Italy
Latitude: 40.011
Longitude: -18.162
Altitude: 117.0
NOAA\ 12 Is Active: false
NOAA\ 14 Is Active: false
NOAA\ 15 Is Active: true
NOAA\ 16 Is Active: false
NOAA\ 17 Is Active: false
NOAA\ 18 Is Active: true
NOAA\ 19 Is Active: true
Meteor\ 3-5 Is Active: false
Meteor\ 2-21 Is Active: false
Resurs\ O1-N4 Is Active: false
Okean-O Is Active: false
SICH-1 Is Active: false
SICH1M Is Active: false
GOES Is Active: false
GMS Is Active: false
MTSAT Is Active: false
Meteosat Is Active: false
NOAA\ 12 Frequency: 137.5000
NOAA\ 14 Frequency: 137.6200
NOAA\ 15 Frequency: 137.6200
NOAA\ 16 Frequency: 137.6200
NOAA\ 17 Frequency: 137.5000
NOAA\ 18 Frequency: 137.9125
NOAA\ 19 Frequency: 137.1000
Meteor\ 3-5 Frequency: 137.3000
Meteor\ 2-21 Frequency: 137.4000
Resurs\ O1-N4 Frequency: 137.8500
Okean-O Frequency: 137.4000
SICH-1 Frequency: 137.3800
SICH1M Frequency: 137.4000
GOES Frequency: 137.5000
GMS Frequency: 137.5000
MTSAT Frequency: 137.5000
Meteosat Frequency: 137.5000
NOAA\ 12 Priority: 1
NOAA\ 14 Priority: 1
NOAA\ 15 Priority: 1
NOAA\ 16 Priority: 1
NOAA\ 17 Priority: 1
NOAA\ 18 Priority: 1
NOAA\ 19 Priority: 1
Meteor\ 3-5 Priority: 2
Meteor\ 2-21 Priority: 1
Resurs\ O1-N4 Priority: 1
Okean-O Priority: 1
SICH-1 Priority: 1
SICH1M Priority: 1
GOES Priority: 5
GMS Priority: 5
MTSAT Priority: 5
Meteosat Priority: 5
NOAA 19 Catalogue Number: 33591
Auto-Decode: true
Alt Sensor: 0
MSA 1: 50
MSA 2: 50
MSA 3: 0
Atmospheric Compensation: false
Auto Save Options: true
Save Temperature Data: false
Check for New Version: true
Update Sat Info: true
Auto Record: false
Auto Update Keplers: false
Last Kepler Update: 0
Geometry: 783x624+0+36
Help Geometry: 783x510+32+126
Own Colormap: true
Use UTC: true
Tearoff Menus: false
Image Set Background: false
Maximum Thumbnails: 25
Log Messages: false
Help Language: EN
Help Font Size: +0
Date Format: %Y-%m-%d %H:%M
Date Format with Seconds: %Y-%m-%d %H:%M:%S
Show All: false
Text Mode 1: 0
Text Mode 2: 0
Text String 1: %N\
	fontsize=18,%Y-%m-%d %H:%M UTC\
	fontsize=12,%D %E %z\
	%r MHz
Text String 2: 
Text Color 1: cyan
Text Color 2: cyan
Text Size 1: 26
Text Size 2: 18
Text X 1: c
Text Y 1: 30
Text X 2: 10
Text Y 2: -30
Text on Movies: true
Text on Composites: false
Temp Scale: false
Temp Black: false
Projection: -
Projection Reference Latitude: 
Projection Reference Longitude: 
Projection Bound North: 
Projection Bound South: 
Projection Bound West: 
Projection Bound East: 
Projection Resampling: bicubic
Projection Scale: 1.000
Projection Min Fill: 0.1
Movie Projection Reference Latitude: 
Movie Projection Reference Longitude: 
Movie Projection Bound North: 
Movie Projection Bound South: 
Movie Projection Bound West: 
Movie Projection Bound East: 
Movie Projection Scale: 1.000
Auto Movie Template: %g-%e
Auto Movie Enhancements: "contrast -b" "MCIR"
Composite Projection Reference Latitude: 
Composite Projection Reference Longitude: 
Composite Projection Bound North: 
Composite Projection Bound South: 
Composite Projection Bound West: 
Composite Projection Bound East: 
Composite Projection Scale: 0.750
Auto Composite Template: %g-%@%Y%m%d-%p-%e
Auto Composite Enhancements: "MSA" "MCIR" "HVCT"
Composite Min Solar Elevation: 10.0
Web Page Template: /usr/local/lib/wx/template1.html
Web Page Enhancement: MSA,MCIR,veg,Pristine
Web Composite Enhancement: 
Web Page Thumbnail Size: 20.0
Web Page Filename: index.html
Web Page FTP Publish: false
Web Page FTP Passive: true
Web Page FTP Host: myisp.someplace.net
Web Page FTP User: 
Web Page FTP Passphrase: 
Web Page FTP Directory: wxtoimg
Web Page Folder Publish: true
Web Page Folder: /home/pi/wxtoimg/web
Web Page Add All: false
Minimum Solar Elevation: 0.0
Exclude from Composites: 
Exclude from Web: 
Minimum Scan Lines: 0
Use MCIR if MSA fails: false
Kepler Host: www.celestrak.com
Kepler Login: 
Kepler Passphrase: 
Use Proxy: false
Proxy Host: 
Proxy Port: 8080

**Comment by fabiomarigliano** [comment]
Fabio
 40.0113
 -18.1624
 117

**Comment by fabiomarigliano** [comment]
```
#!/usr/bin/env python3
import ephem
import time
import sys

timezone= +1 + time.localtime().tm_isdst
date = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(int(sys.argv[1])-(timezone*60*60)))

obs=ephem.Observer()
obs.lat='40.016'
obs.long='-18.1638'
obs.date = date

sun = ephem.Sun(obs)
sun.compute(obs)
sun_angle = float(sun.alt) * 57.2957795 # Rad to deg
print(int(sun_angle))
```

**Comment by fabiomarigliano** [comment]
they are in order as you asked for them

**Comment by reynico** [comment]
everything seems fine over there.
could yo please upload the output of one or two entries of `mail`?  those are the logs for the sat passes

**Comment by fabiomarigliano** [comment]
To: pi@raspberrypi
Message-Id: <E1l0i8w-0005ZS-3o@raspberrypi>
From: pi@raspberrypi
Date: Sat, 16 Jan 2021 10:45:14 +0100

INFO : Starting rtl_fm record
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 49.60 dB.
Tuner error set to 1 ppm.
Tuned to 138392500 Hz.
Oversampling input by: 32x.
Oversampling output by: 1x.
Buffer size: 4.27ms
Sampling at 1920000 S/s.
Output at 60000 Hz.
Signal caught, exiting!

User cancel, exiting...
INFO : Bulding pass map
wxmap: warning: could not find matching pass to build overlay map.
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
wxtoimg: warning: no specific NOAA satellite (using NOAA 12/14 series model)
wxtoimg: warning: No map to use for MSA enhancement
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
wxtoimg: warning: no specific NOAA satellite (using NOAA 12/14 series model)
wxtoimg: warning: No map to use for MSA enhancement
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png'
Satellite: NOAA
Status: signal processing............................
Gain: 14.6
Channel A: 1 (visible)
Channel B: 4 (thermal infrared)
Traceback (most recent call last):
  File "/home/pi/raspberry-noaa/post.py", line 23, in <module>
    res = api.media_upload(filename)
  File "/usr/local/lib/python3.7/dist-packages/tweepy/api.py", line 231, in media_upload
    file_type = imghdr.what(filename, h=h) or mimetypes.guess_type(filename)[0]
  File "/usr/lib/python3.7/imghdr.py", line 16, in what
    f = open(file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/wx/image//NOAA1820210116-102634-MCIR-precip.jpg'
rm: impossibile rimuovere '/home/pi/raspberry-noaa/map/NOAA1820210116-102634-map.png': File o directory non esistente
INFO : Posting to Twitter
INFO : Deleting audio files

**Comment by reynico** [comment]
okay, 
seems like your `predict.qth` settings are wrong, should be

```
Fabio
40.0113
18.1624
117
```
(Lon negated)

**Comment by fabiomarigliano** [comment]
ok i try to change i will tell you in the next step. Thanks

**Comment by maxzega** [comment]
Fabio is ok now with no negative longitude?

**Comment by fabiomarigliano** [comment]
> Fabio is ok now with no negative longitude?

 No I always have the same problems, tomorrow I format and reinstall everything

**Comment by maxzega** [comment]
Ok Thanks for the info

**Comment by fabiomarigliano** [comment]
I solved by installing again. thank you all for the support I close
