### ISSUE TITLE
Error in the pass list

### ISSUE THREAD

**Issue by fabiomarigliano** [reynico/raspberry-noaa#118]
Hi everyone, I regularly receive pictures of both the noaa and the Meteor. If I run the atq command I regularly see the correct steps with my time. The problem arises when I go to see the steps in the web browser, in the steps menu it shows me the list with the wrong steps, in particular they are steps with 4 hours less. Example if a satellite passes at 19PM on the web I see it at 15PM, but the system receives it regularly at 19PM it is only an error that I find in the request of the strings. Can anyone tell me what can be caused?
Thanks
![Schermata 2021-01-20 alle 15 47 51](https://user-images.githubusercontent.com/46231794/105191720-b270d500-5b37-11eb-9bed-d797063648dd.png)

**Comment by reynico** [comment]
Hi Fabio, please refer to https://github.com/reynico/raspberry-noaa/blob/master/WEBPANEL.md#satellite-pass-dates-are-wrong

**Comment by fabiomarigliano** [comment]
> Hi Fabio, please refer to https://github.com/reynico/raspberry-noaa/blob/master/WEBPANEL.md#satellite-pass-dates-are-wrong


ok thanks solved
