### ISSUE TITLE
Automatic configuration of RTLSDR-Dongle fails

### ISSUE THREAD

**Issue by df6dbf** [reynico/raspberry-noaa#12]
In fresh Installations the automatic config of RTLSDR-Dongles failed. Have to configure the Device by Hand. Rest of Installation Script work fine!

Kind Regards, Holger

**Comment by reynico** [comment]
Hi Holger! hope you're doing well.
Any log output of the error?

**Comment by df6dbf** [comment]
Sorry, have no log saved. I am familar with RTLSDR so i configured by hand. But a little suggestion: Take a look here: https://github.com/steve-m/kalibrate-rtl it would be nice to have a automated frequency fix of the SDR-Dongles. :) Kind Regards, Holger

**Comment by reynico** [comment]
Thanks Holger! I'll give a try. Will close this issue for now, please feel free to reopen if anything else happens with the setup
