### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by klikis** [reynico/raspberry-noaa#125]
Why can't I see the list of steps? where did I go wrong?
![Cattura](https://user-images.githubusercontent.com/9518512/106191115-bbeae480-61aa-11eb-9ef1-44333db13f79.PNG)

**Comment by jekhokie** [comment]
@klikis Did you run ./schedule.sh after you performed the install? That script is what creates the passes, and by default is run at midnight every night (see crontab -l), so the first time you install you need to run the ./schedule.sh script unless you want to wait until midnight.

**Comment by klikis** [comment]
many thanks you were clear and kind.
