### ISSUE TITLE
Idea: Receiving of ISS

### ISSUE THREAD

**Issue by df6dbf** [reynico/raspberry-noaa#15]
It seems that this time only WAV-Files from ISS catched. 
What about the APRS-Downlink on 145.825? Data handling may be possible with multimon-NG and pymultimonaprs to feed the APRS-Network.

73 Holger

**Comment by kalidassingh** [comment]
I have an error in "schedule_iss.sh". Please help me

pi@raspberrypi:~/raspberry-noaa $ ./schedule_iss.sh

./schedule_iss.sh: 8: /home/pi/raspberry-noaa/common.sh: Syntax error: "(" unexpected

**Comment by surfrod** [comment]
I also have the same syntax error in schedule_iss.sh.

That part of the script (note set -x is uncommented locally)
#!/bin/sh

## debug
set -x

. ~/.noaa.conf
. "${NOAA_HOME}"/common.sh
SAT_MIN_ELEV=10

PREDICTION_START=$(/usr/bin/predict -t "${NOAA_HOME}"/predict/amateur.tle -p "${1}" | head -1)
PREDICTION_END=$(/usr/bin/predict -t "${NOAA_HOME}"/predict/amateur.tle -p "${1}" | tail -1)

and the mail log:

From: root@raspberrypi (Cron Daemon)
To: pi@raspberrypi
Subject: Cron <pi@raspberrypi> /home/pi/raspberry-noaa/schedule.sh
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/pi>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=pi>
Message-Id: <E1kQ0dU-0003x3-O8@raspberrypi>
Date: Wed, 07 Oct 2020 00:01:04 -0400

+ . /home/pi/.noaa.conf
+ NOAA_HOME=/home/pi/raspberry-noaa
+ NOAA_OUTPUT=/var/www/wx
+ METEOR_OUTPUT=/var/www/wx/meteor
+ NOAA_AUDIO=/var/ramfs
+ SAT_MIN_ELEV=30
+ METEOR_MIN_ELEV=30
+ SUN_MIN_ELEV=10
+ LOG_LEVEL=DEBUG
+ LAT=39.486
+ LON=-74.471
+ BIAS_TEE=
+ DELETE_AUDIO=true
+ export LOG_LEVEL
+ . /home/pi/raspberry-noaa/common.sh
+ . /home/pi/.noaa.conf
+ NOAA_HOME=/home/pi/raspberry-noaa
+ NOAA_OUTPUT=/var/www/wx
+ METEOR_OUTPUT=/var/www/wx/meteor
+ NOAA_AUDIO=/var/ramfs
+ SAT_MIN_ELEV=30
+ METEOR_MIN_ELEV=30
+ SUN_MIN_ELEV=10
+ LOG_LEVEL=DEBUG
+ LAT=39.486
+ LON=-74.471
+ BIAS_TEE=
+ DELETE_AUDIO=true
+ export LOG_LEVEL
/home/pi/raspberry-noaa/schedule_iss.sh: 8: /home/pi/raspberry-noaa/common.sh: S
yntax error: "(" unexpected
INFO : Pass prediction in progress
INFO : Pass prediction in progress
INFO : Pass is above 30, that is OK for me
METEOR-M2 20201007-090829 86
warning: commands will be executed using /bin/sh

......

It looks like it just exits out of schedule_iss.sh

**Comment by reynico** [comment]
ISS is now fully supported in `master`.
