### ISSUE TITLE
Good images cropped to narrow band

### ISSUE THREAD

**Issue by ant-thomas** [reynico/raspberry-noaa#16]
Not sure if this is a feature or an issue. Or I'm more so looking for a bit of info/advice.
I've made a pretty janky indoor dipole antenna with some 1.5mm2 copper cable, also added an amplifier. Was previously using the amp for an ADS-B setup, just changed the antenna.
Not tuned in any way, antenna length is about right.

![image](https://user-images.githubusercontent.com/1029851/86742091-c50a3d80-c02f-11ea-8eaa-cb436cf78cfe.png)

Most passes result in some signal, but generally poor.
Occasionally there's a pass which is very good, but the output image is cropped to what looks like the good section, rather than the full length of the pass/recording.

Is this supposed to happen to remove any noise across the "bad" area?
Unsurprisingly the good area has my location near enough centered.

Eg....
![image](https://user-images.githubusercontent.com/1029851/86741725-84aabf80-c02f-11ea-9d97-4685452bfeb2.png)

Great to see the setup works, but would be interested to see the full pass on "good" receive.

**Comment by ant-thomas** [comment]
Interestingly just had a full pass with the good bit in the middle, along with the rest noisy....
Will eventually look at a better antenna, but would be good to know if there's a setting to be changed to prevent the crop?

![image](https://user-images.githubusercontent.com/1029851/86772792-9c447100-c04c-11ea-93f4-9dc3c064403d.png)

**Comment by reynico** [comment]
Hi Thomas! Sure, append `-A` to the wxtoimg line

```
         -A         all (do not cut top and bottom low signal sections)
```


So it'll end up like

```
        /usr/local/bin/wxtoimg -A -o -m "${NOAA_HOME}/map/${3}-map.png" -e "$i" "${NOAA_AUDIO}/audio/${3}.wav" "${NOAA_OUTPUT}/image/${FOLDER_DATE}/${3}-$i.jpg"
```

**Comment by ant-thomas** [comment]
Fantastic, thank you!
