### ISSUE TITLE
how install new release please ?

### ISSUE THREAD

**Issue by F1SMV** [reynico/raspberry-noaa#17]
GE
i would like test new release but i dont understand how install..can you add one little info . Thank in advance

eric

**Comment by reynico** [comment]
Hi Eric, there is no way to do an incremental install yet so you need to delete (or move to another directory) the config files generated by install.sh, as well as the installed packages.

**Comment by F1SMV** [comment]
thank you it is clearer for the beginners, but I meet problems of rights which I did not have before and I have difficulty.
example after ./schedule.sh:
  mkdir: unable to create directory "/ var / ramfs": Permission not granted
mkdir: unable to create directory "/ var / ramfs": Permission not granted
METEOR-M2 20200711-220345 68
warning: commands will be executed using / bin / sh
but i found soluce i I entered all the command lines manually and the error messages disappeared, so apparently during the install.sh all the lines are not taken into account except error on my part
----------
dont want install numpy 1.18.1...i install 1.9 latest
------
i received a big wave file after meteor pass; but to have taken the directories correctly because no image is displayed the meteor_demod directory must be in / home / pi / raspberry-noaa or in / home / pi / raspberry-noaa / software? which would explain why no image appeared can be

---------
in log
Traceback (most recent call last):
  File "/home/pi/raspberry-noaa/sun.py", line 5, in <module>
    timezone = change_tz
NameError: name 'change_tz' is not defined
/home/pi/raspberry-noaa/receive_meteor.sh: ligne 12 : [:  : nombre entier attendu comme expression

here we are in utc +2 , may be i must write +2 ?

thank for your help
Eric

**Comment by reynico** [comment]
Hi, for positive values just write 2.

**Comment by F1SMV** [comment]
thank for info
