### ISSUE TITLE
Directories Errors

### ISSUE THREAD

**Issue by HalloweenMagic** [reynico/raspberry-noaa#22]
Hello!
After the run of autoinstall, there are some issues with directories.
For example: audio directory doesn't exist and METEOR image are saved into NOAA and inside METEOR there aren't anything.

I hope I can help you with this report :)

![2020-07-16_122725](https://user-images.githubusercontent.com/67958671/87660887-11f0c100-c760-11ea-9a51-425667c9f109.jpg)
![2020-07-16_122914](https://user-images.githubusercontent.com/67958671/87660889-12895780-c760-11ea-9d33-96f78b724973.jpg)
![2020-07-16_122701](https://user-images.githubusercontent.com/67958671/87660894-13ba8480-c760-11ea-9a00-4ad3dfe61e29.jpg)

**Comment by tomamdy** [comment]
Yes, You are right . I like this software, but it has some issues.

**Comment by reynico** [comment]
Hi! Thank you, I'll push an update to fix this.

**Comment by HalloweenMagic** [comment]
> Hi! Thank you, I'll push an update to fix this.

Thanks a lot! 
There is another problem with predict: if you try to use it, you can enter immediatly inside "Configuration Mode", without possibility to choosing options from the menu

**Comment by reynico** [comment]
Hi,
I've added a boolean to either store or not the received audio. git fetch && git pull to grab the latest changes and then do a 
```
echo "DELETE_AUDIO=false" >> ~/.noaa.conf
```

**Comment by Crosswalkersam** [comment]
@HalloweenMagic 

I had that issue with pridict aswell. To solve it, simply run:

`cd ~/.predict`

and then download the missing files from github:

`wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.db`

`wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.tle`

`wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.qth`

after that, run `predict` again, it should work now.
