### ISSUE TITLE
No capture

### ISSUE THREAD

**Issue by MammaMia2020** [reynico/raspberry-noaa#23]
Hi and thanks for this script!
This morning I try to receive METEOR, but despite it having passed over my head, I don't know if the software has started receiving. Yesterday everything worked, not this morning. The only image produced is from NOAA, but only a small piece.

Checking with ORBITRON, I don't find myself with the dates and times.
Latitude and longitude is correct.

If I start "predict", only the page opens to configure latitude and longitude and the menu for the other functions does not appear.

Is it a bug?

![2020-07-16_164127](https://user-images.githubusercontent.com/68387601/87685529-ce0fb300-c783-11ea-80fc-62e470372978.jpg)

This is the NOAA image cutted

![NOAA1920200716-073431-MCIR-precip](https://user-images.githubusercontent.com/68387601/87685600-e089ec80-c783-11ea-9026-d9cb6bfe1c35.jpg)

And this is the problem with predict

![2020-07-16_164640](https://user-images.githubusercontent.com/68387601/87685701-fd262480-c783-11ea-9a94-6edc463da3b5.jpg)

I just see this screen:

![2020-07-16_164651](https://user-images.githubusercontent.com/68387601/87685727-044d3280-c784-11ea-80a8-d631ea00f875.jpg)

**Comment by reynico** [comment]
Hi, 
there's a check here: https://github.com/reynico/raspberry-noaa/blob/master/receive_meteor.sh#L12-L15 to avoid low sun elev passes of Meteor since the IR radiometers seems to be broken.  If you want to receive and decode all passes just comment or delete the line 14 (exit 0)

**Comment by Crosswalkersam** [comment]
@MammaMia2020 

To fix the issue with predict, simply do this:

`cd ~/.predict`

and then download the missing files from github:

`wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.db`

`wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.tle`

`wget https://raw.githubusercontent.com/kd2bd/predict/master/default/predict.qth`

after that, run `predict` again, it should work now.
