### ISSUE TITLE
No Meteor images

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#29]
I get no images in the script. What is wrong.?

METEOR-M220200725-091111.qpsk                      25-Jul-2020 10:29           128147320
METEOR-M220200725-091111.wav                       25-Jul-2020 10:21           341759360
METEOR-M220200726-085112.qpsk                      26-Jul-2020 09:15           132082368
METEOR-M220200726-085112.wav                       26-Jul-2020 09:08           352245120
METEOR-M220200727-083115.qpsk                      27-Jul-2020 08:56           134060214
METEOR-M220200727-083115.wav                       27-Jul-2020 08:48           357520768

**Comment by reynico** [comment]
Hi, have you checked the `/var/www/wx/image` folder?

**Comment by tomamdy** [comment]
Ofcourse
![2020-08-02 19_22_24-Window](https://user-images.githubusercontent.com/67389269/89163999-070e9c80-d566-11ea-8678-918f02c152d3.png)
![2020-08-02 19_20_53-Window](https://user-images.githubusercontent.com/67389269/89164011-0a098d00-d566-11ea-83e7-d8e7fc5b46d9.png)

**Comment by alexnxt20** [comment]
Can you post your ".noaa.conf" file located in /home/pi/?

I had a problem similar to this. The ./receive_meteor.sh script breaks if the DELETE_AUDIO variable is not either "true" or left blank. If you type DELETE_AUDIO=false in the .nooa.conf file, it will not provide images, if you want to save audio, leave the DELETE_AUDIO= field blank.

**Comment by tomamdy** [comment]
Here the file, I hope its gives the result.


NOAA_HOME=/home/pi/raspberry-noaa
NOAA_OUTPUT=/var/www/wx
METEOR_OUTPUT=/var/www/wx/meteor
NOAA_AUDIO=/var/ramfs
SAT_MIN_ELEV=30
METEOR_MIN_ELEV=30
SUN_MIN_ELEV=10
LOG_LEVEL=DEBUG
LAT=change_latitude
LON=change_longitude
BIAS_TEE="enable_bias_tee"
DELETE_AUDIO=true

**Comment by tomamdy** [comment]
Now it works again. I only have installed the scripts again.
