### ISSUE TITLE
Cant receive any picture from sdr. 

### ISSUE THREAD

**Issue by shazlia89** [reynico/raspberry-noaa#33]
Hello everyone,sorry for my bad english. Im just wondering why i cant receive any picture from sdr. Currently i lived in Malaysia. I think most likely i configured the predict program wrongly. and i think i have a wrong position for the satellite. 
![NOAA1920200815-084054-map](https://user-images.githubusercontent.com/69812633/90423422-0130c380-e0ef-11ea-9c32-47d68336ed3e.png)
![NOAA1520200814-213055-map](https://user-images.githubusercontent.com/69812633/90423445-0e4db280-e0ef-11ea-809d-1d3557c13fe8.png)

 May i know what causes this problem? Thanks alot !!

**Comment by reynico** [comment]
Hi @shazlia89 !

Those images belongs to the map that WxToIMG uses to overlay received images. Have you checked the `/var/www/wx/image` directory? Take a look through the browser at http://your.raspberry.pi.ip/image/

**Comment by reynico** [comment]
Closing by inactivity
