### ISSUE TITLE
date: invalid date ‘@’

### ISSUE THREAD

**Issue by ant-thomas** [reynico/raspberry-noaa#35]
I've been using raspberry-noaa for a few months without issue.
Over the last few days there's been no predictions. I've run the job manually and the error is...

`date: invalid date ‘@’`

I think I may have done an `apt upgrade` before this happened. But I didn't think it would cause such an issue.
Any idea how I can go about diagnosing this one?

**Comment by reynico** [comment]
hi!
what's the job you ran? `./schedule.sh`?

**Comment by reynico** [comment]
Closing by inactivity

**Comment by ant-thomas** [comment]
Hi,
Yes, running `schedule.sh` . Not changed anything in that. Only a system `sudo apt upgrade`
