### ISSUE TITLE
Not an Issue: METEOR-M M2 IR channel activated

### ISSUE THREAD

**Issue by HZ1SF** [reynico/raspberry-noaa#44]
Hi @reynico , I don;t know if you heard but I have seen multiple accounts on twitter posting photos from METEOR-M M2 at night because of the activation of the IR channel. Is there anything we need to do to receive these transmissions?

**Comment by reynico** [comment]
Hi!
I'll push an update to decode the APID 68

**Comment by HZ1SF** [comment]
Thanks @reynico , when you're done can you please explain what do we need to do? Will I need to redo the whole installation or something else? please forgive my noobness.

**Comment by reynico** [comment]
Hi @saudfs just update your master copy

```
cd ~/raspberry-noaa
git fetch && git pull
```

Recent changes includes a fix on rectify (I've also open a PR on upstream https://github.com/dbdexter-dev/meteor_rectify/pull/4) and enable receive_meteor.sh to parse the .dec file just on APID 68 (IR Channel)

**Comment by ghost** [comment]
Fantastic, thanks a lot Nico, I'll update in a few seconds.

**Comment by ghost** [comment]
Nico, I've just posted Meteor image on Twitter (night time here in Italy) but the result is black.

**Comment by HZ1SF** [comment]
Thanks @reynico , I'll do that now.

**Comment by reynico** [comment]
Hi @Indr1d-C0ld ! could you please upload the .dec file somewhere so I can check over it?

**Comment by ghost** [comment]
Sure my friend:

https://drive.google.com/file/d/1TMD-CjrmgiIbBXzqpk2K0orIw75RFuWX/view?usp=sharing

**Comment by reynico** [comment]
Yes, seems like the bmp to jpg conversion brokes something important at the image file (maybe screwed up headers?)

I pushed a last time commit to fix that: https://github.com/reynico/raspberry-noaa/commit/c842323a22c4f89d4b95fc805df75ca0b115d465

It just feeds rectify with the raw BMP file instead of converting to JPG then moving to rectify

**Comment by ghost** [comment]
Perfect, awesome work and fast too... keep in touch dear dev, in the meanwhile I've modified those 2 lines in receive_meteor.sh

**Comment by reynico** [comment]
Great! I'll close this issue for now, feel free to re open it if needed
