### ISSUE TITLE
error in longtitude

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#54]
I get this error. Could you explain what that means.

/home/pi/.noaa.conf: line 9: syntax error near unexpected token `('
/home/pi/.noaa.conf: line 9: `LAT=Decimal latitude and longitude coordinates for Enkhuizen (Netherlands): 52.7033'

**Comment by reynico** [comment]
Hi @tomamdy !
Could you please paste your current `/home/pi/.noaa.conf` file contents?

**Comment by tomamdy** [comment]
NOAA_HOME=/home/pi/raspberry-noaa
NOAA_OUTPUT=/var/www/wx
METEOR_OUTPUT=/var/www/wx/meteor
RAMFS_AUDIO=/var/ramfs
SAT_MIN_ELEV=30
METEOR_MIN_ELEV=30
SUN_MIN_ELEV=10
LOG_LEVEL=DEBUG
LAT=change_latitude
LON=change_longitude
BIAS_TEE="enable_bias_tee"
DELETE_AUDIO="true"
FLIP_METEOR_IMG="true"

**Comment by reynico** [comment]
Hmm, seems like the installation process didn't setup your config file.

You'll need to edit this:
```
LAT=change_latitude
LON=change_longitude
BIAS_TEE="enable_bias_tee"
```

so `change_latitude` is your latitude (i.e. -34.5532), `change_longitude` is your longitude (i.e. -58.4411) and `BIAS_TEE` should be `BIAS_TEE=""` if you're not using bias tee to power up a LNA with your dongle.

**Comment by tomamdy** [comment]
I have changed, but still got this mail:

/home/pi/.noaa.conf: regel 9: 52.70333: opdracht niet gevonden
/home/pi/.noaa.conf: regel 9: 52.70333: opdracht niet gevonden

Regards,
Tom

**Comment by reynico** [comment]
Hi @tomamdy sorry for the delay. I've been trying to replicate this error but I couldn't get to it.

Let's start from the beginning

1. How's your `.noaa.conf` file looking right now?
2. What happens when you manually call `/home/pi/raspberry-noaa/schedule.sh` ?
3. Where/when does that error `/home/pi/.noaa.conf: regel 9: 52.70333: opdracht niet gevonde` happens?

**Comment by tomamdy** [comment]
Today I have installed Your latest release and anothe antenna. I think it should work now. Nice webinterface,

Tom
