### ISSUE TITLE
test_reception.sh

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#55]
I have tried this under windows10 and ncat doesn't works under win10. May be there is another program then ncat for windows ?

**Comment by reynico** [comment]
Hi!
I'm not a Windows user so I don't know about any netcat equivalent )-:

The only thing that comes to my mind is an "offline" way to test the reception.  So on the Raspberry PI you run 

```
rtl_fm -f 90.3M -s 256k -g 45 -p 55 -E deemp -F 9 - | sox -traw -r256k -es -b16 -c1 -V1 - -tmp3 /var/www/wx/audio/recording.mp3
```

for a minute or so, then ctrl C to stop the execution. Then at http://your.raspberry.pi.ip/audio/recording.mp3 you can listen the recording.
