### ISSUE TITLE
webpanel

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#64]
Could it be possible that I change the webpanel in Dutch or English and how to do that ?

**Comment by reynico** [comment]
Hi @tomamdy !

sure, edit the file `/var/www/wx/Config.php`. Change the line

```
  'lang' => 'es'
```

to

```
  'lang' => 'en'
```

There's one more thing you may want to edit: timezone for web panel.
Edit `/var/www/wx/header.php`

```
  date_default_timezone_set('America/Argentina/Buenos_Aires');
```

here's a list of timezones: https://www.php.net/manual/en/timezones.php

**Comment by tomamdy** [comment]
Thank you, Nico. It works.
