### ISSUE TITLE
Issue: Time stamp on image versus file time in web based image viewer

### ISSUE THREAD

**Issue by m0nde** [reynico/raspberry-noaa#65]
This may not be an issue but a feature or my misunderstanding as I am new to this only starting two days ago.

An example of the issue

In the web based images I have a NOAA 15 image 18/11/2020 16:20:15 
The images when viewed is stamped 18/11/2020 19:20

Please can some explain 

Thanks

Nigel M0NDE
![pic2](https://user-images.githubusercontent.com/9598811/99587588-321bdf80-29e1-11eb-9c6f-ed2785ff9b07.png)
![pic1](https://user-images.githubusercontent.com/9598811/99587629-3e07a180-29e1-11eb-9024-aae653fa3db7.png)

**Comment by reynico** [comment]
Hi Nigel! I forgot to document the timezone stuff. see my comment here https://github.com/reynico/raspberry-noaa/issues/64#issuecomment-729610113

**Comment by m0nde** [comment]
Issue sorted by edit of /var/www/wx/header.php
Thank you Nico
