### ISSUE TITLE
pi mail gives this notice.

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#67]
INFO : The system doesn't have enough space to store a Meteor pass on,
Could it be that there are to much pictures

**Comment by reynico** [comment]
Hi Tom!

That's ok if you're running raspberry-noaa on a system that has less than 2000MB of RAM. There's a switch in the code that stores the Meteor pass in a ramfs partition to speed up things, but that's available only if there's enough memory.

**Comment by tomamdy** [comment]
Sorry, I like your siftware, but I have still problems with receiving.
![NOAA1820201121-102401-MCIR](https://user-images.githubusercontent.com/67389269/99879131-a2ee1200-2c02-11eb-82f5-13b46cada6f0.jpg)

**Comment by reynico** [comment]
There's not much to do from software side about that. Seems like there's a lot of noise near you (broadcast FM?) but this is nothing fixable from software, sorry

**Comment by tomamdy** [comment]
But a friend of me has the same problem and under Windows no problems.

**Comment by tomamdy** [comment]
Here he receives by windows.. http://www.enkhuizen-meteo.nl/noaa.html

**Comment by schelhaas** [comment]
By the way, I have the same experience for the last 3 days. I thought that the reason is my antenna. 
Here is how it looks when I receive NOAA. 
![F6455BEE-B92F-4793-A9DA-3EF405C9A148](https://user-images.githubusercontent.com/25137403/99884092-c5e0ec00-2c2b-11eb-9c34-b018499af5a7.jpeg)

Before reinstalling my system 3 days ago NOAA was good.

**Comment by tomamdy** [comment]
NOAA19,  Elevation: 74°,21/11/2020 17:13:50 was ok again. I am no sure, but could it be 
that the scandisk has not enough space, because the old images stay on the card. 
Should it be better that they automatic remove ?

**Comment by schelhaas** [comment]
I just re-installed the version I downloaded 4 days ago and it now looks much better. Has there been a change lately? I just recognized a new language 3 days ago and in that version I got bad pictures. 

This is how it looks after my “downgrade”:
![DFC1E4D9-1CB8-48E7-A161-53D0436FFDEE](https://user-images.githubusercontent.com/25137403/99887372-12d0bc80-2c44-11eb-81e0-279d78b5aa38.jpeg)

**Comment by tomamdy** [comment]
This was mine.
![NOAA1820201121-201544-MCIR-precip](https://user-images.githubusercontent.com/67389269/99889344-0c464300-2c4c-11eb-9dba-bf1673415b7a.jpg)
