### ISSUE TITLE
[Error] Changing Webpage Language Not Successful

### ISSUE THREAD

**Issue by MihajloPi** [reynico/raspberry-noaa#70]
Hi, I've tried to change webpage language from Spanish to English by changing Config.php file, but the webpage is still in Spanish. Any ideas?

`<?php
return (object) array(
  'base_url' => '/images/',
  'img_per_page' => 12,
  'lang' => 'en'
);
?>
`

**Comment by tomamdy** [comment]
<?php return (object) array(  'base_url' => '/images/',  'img_per_page' => 12,  'lang' => 'en');?>
 
For me, that works ok. May be pressing in Your browser F5, that refreshs our browser.

Tom

**Comment by MihajloPi** [comment]
Yes, I refreshed my browser multiple times, even rebooted Raspberry Pi, but it's still in Spanish.

**Comment by tomamdy** [comment]
Should I sent You my Config.php?

**Comment by MihajloPi** [comment]
Yes, thank you!

**Comment by tomamdy** [comment]
[config.txt](https://github.com/reynico/raspberry-noaa/files/5608427/config.txt)

**Comment by tomamdy** [comment]
Make extension php

**Comment by MihajloPi** [comment]
I copied everything, renamed it Config.php but website is still in Spanish.


![Capture](https://user-images.githubusercontent.com/25284848/100464281-9c154280-30cd-11eb-82c7-2e1c332cb0fb.JPG)

**Comment by reynico** [comment]
Hi!

Keep in mind that you need to edit the Config.php inside `/var/www/wx/`

**Comment by MihajloPi** [comment]
Ohhh so that was the problem! I totally forgot about `/var/www/wx/` path! Thank you!
