### ISSUE TITLE
Install Script

### ISSUE THREAD

**Issue by jpekala** [reynico/raspberry-noaa#8]
First I would like to say this is a wonderful script and setup. Thank you for putting so much time into building this for everyone to use. If i may, I would like to make a couple of suggestion that i noticed while using you script a couple of time for installs. 

If possible could you add libjpeg9 libjpeg9-dev to the packages section of the installer. Python pip would not install pillow with out them installed. 

------

Also for the predict setup. I noticed on a new install like mine you only check for the predict.qth file and if it does not exist it tries to copy it to the .predict folder which also does not exist. This folder only exists if you run the predict program once. 

My suggestion would be to add the following to your predict config section:

```
if [ -d "$HOME/.predict" ] && [ -e "$HOME/.predict/predict.qth" ]; then
    log_done "$HOME/.predict/predict.qth already exists"
else
    mkdir "$HOME/.predict"
    cp "templates/predict.qth" "$HOME/.predict/predict.qth"
    log_done "$HOME/.predict/predict.qth installed"
fi
```

------

Also the same for the cronjob section. The file /var/spool/cron/crontabs/pi only exists if you have ran crontab -e prior to your install script. 

My suggestion would be to run it for them and have them copy and paste your cronjob into it. This way it enables the scheduler. outside of that you would have to run as root and copy over a cronjob template to /var/spool/cron/crontabs/pi

------

One last suggestion would be to run wxtoimg at the end of your install script and have the user accept the licensing agreement for wxtoimg. Because if they do not accept it will the program will not do anything until it have been accepted.

**Comment by reynico** [comment]
Thank you! I just merged the PR.
