### ISSUE TITLE
[enhancement] Built-in monitoring dashboard

### ISSUE THREAD

**Issue by pineapplee85** [reynico/raspberry-noaa#80]
Hi there,

Just wondering what you thought about this idea?

Wondering if you could have a dashboard on the webpage (separate page) that shows stats such as CPU Usage and temp, WiFi strength, pass signal strength, satellite health eg. uptime or battery temp (if available from an external source?), cpu clock speed or any other data that might be useful in cool graphs and dials? Maybe something like this:
[https://jorge.maroto.me/content/images/2020/06/Screenshot-2020-06-08-at-00.59.38-1.png](url)

It would be cool to have it built into the script as a yes or no if you want it to install, however I understand this would require adding in lots of other steps and files into the script and may not be worth your time.

Thanks for the great project!
Ethan

**Comment by reynico** [comment]
Hi Ethan!
Looks great but also resource-intensive. That's [Grafana](https://grafana.com/), it's an analytics/monitoring solution, really cool for sure but I want to keep this system as simple as possible. Anyways I can help you out installing this on your device so you can use it.

**Comment by MihajloPi** [comment]
Hi Nico! I would also like to install Grafana! Be sure to post an installation guide!

**Comment by pineapplee85** [comment]
Hi Reynico,

I had a look at this but it did not seem to work, I also then had a go at node-red but to no joy. 
If you could help me that would be great.

Thanks!

**Comment by reynico** [comment]
https://grafana.com/grafana/download?platform=arm

```
wget https://dl.grafana.com/oss/release/grafana-7.3.6.linux-armv6.tar.gz
tar -zxvf grafana-7.3.6.linux-armv6.tar.gz
```

then 
```
cd grafana-7.3.6
./bin/grafana-server
```

should be enough.

**Comment by pineapplee85** [comment]
Hi there,

I have Grafana installed however, am not sure how to setup a dashboard. This is what I was confused with. 
Is there a tutorial? I could not find one anywhere.

Thanks!

**Comment by reynico** [comment]
This is one of the best places to learn/ask about grafana I guess: https://www.reddit.com/r/grafana/

Since I'm not planning to add enhanced monitoring to raspberry-noaa I'll close this issue for now. Feel free to reopen if needed
