### ISSUE TITLE
No images from passes.

### ISSUE THREAD

**Issue by Anjum9694** [reynico/raspberry-noaa#86]
Hi so the passes were generated by scheduler, I left it overnight but next day there were no images from the passes. I tested with rtl_test to be sure my v3 was working with the pi. What could be the reason for it?

![da](https://user-images.githubusercontent.com/31078090/102851923-d9f05700-443e-11eb-9cfc-42d27c5f8e49.JPG)
![Capture](https://user-images.githubusercontent.com/31078090/102851936-e1176500-443e-11eb-9bc6-73474ec6f706.JPG)

**Comment by reynico** [comment]
seems like the `/var/www/wx/` folder has the wrong permissions.

```
sudo chown pi:pi /var/www/wx
```

that should be enough

**Comment by Anjum9694** [comment]
I applied the permission fixes. I will be submitting here the changes I am doing.

I noticed the schedule script doesn't update the tle database of predict, it's way off! 
![daaaa](https://user-images.githubusercontent.com/31078090/102962056-d1b01e80-4507-11eb-8cc2-7a3ed3cd6c77.JPG)
![dasdasdad](https://user-images.githubusercontent.com/31078090/102962059-d379e200-4507-11eb-8d16-0b656fd64f00.JPG)

I temporarily moved the weather.tle from raspberry-noaa predict folder as predict.tle. Now I am doing a visible pass calculation.
![Capture43](https://user-images.githubusercontent.com/31078090/102962555-e9d46d80-4508-11eb-8d36-3f3112c027ad.JPG)

The timing is off by about 5 hours. The date command returns the correct timezone. I'm not sure where needs to be changed. That's all for now.

**Comment by reynico** [comment]
Hi, as far I know, predict uses a different path for its database. raspberry-noaa uses a custom path for it.

**Comment by Anjum9694** [comment]
![Capture](https://user-images.githubusercontent.com/31078090/103088132-af9fc480-460b-11eb-861c-509a182a3dcc.JPG)
I did a reinstall. Got a standard in syntax error there. My timezone is GMT +5 so I wrote +5

**Comment by reynico** [comment]
Hi, for positive timezones it is just the number (i.e. 5)

**Comment by Anjum9694** [comment]
Thanks! I am getting accurate passes now, which I hope will result in pictures finally!
Just one more thing, sometimes when the scheduler is run I get 
date: invalid date ‘@’
date: invalid date ‘@’
date: invalid date ‘@’
date: invalid date ‘@’

So when crontab is run and the error occurs there are no passes for the day.

**Comment by reynico** [comment]
Hi! Sorry for the delay, I completely forgot this issue. Have you figured out your problem?

**Comment by dom1706** [comment]
Hello and I would like to thank reynico for his great job !
I've the same problem: no pictures but the other page with passes is ok.
I've this error message: 
`convert: unable to open image `/var/www/wx/images/NOAA1520210104-091024-MCIR-precip.jpg': Aucun fichier ou dossier de ce type @ error/blob.c/OpenBlob/2874.`
I have put this to give the right permissions but it doesn't help: sudo chown pi:pi /var/www/wx
What could be my problem ?
Best regards.

**Comment by Anjum9694** [comment]
Hey Nico, I have uninstalled it for now. Since it's working for others I figured it's best to reimage my sd card and start over. Will update this thread to let you know how it goes. Best regards and a Happy New Year.

**Comment by surfrod** [comment]
ok, against my better judgement ( 🥇 ) I did a fresh pull and restore.

But now, not getting any images and see error messages galore like:
INFO : Bulding pass map
Satellite: NOAA 19
Pass Start: 2021-01-05 12:06:46 UTC
Pass Duration: 15:34
Elevation: 62
Azimuth: 288
Direction: southbound
..INFO : Decoding image
Satellite: NOAA 19
Status: signal processing...
wxtoimg: error: out of memory in line 1412 of noaa.c
wxtoimg: warning: enhancement ignored: could not find a NOAA/GOES sensor 4 image
INFO : Decoding image

I have 54Gig free disk memory, and /var/www/wx permissions are fine.  .noaa.conf looks good.

Just did a mv raspberry-noaa to OLDraspberry-noaa and did a new git pull; cd; ./install.sh

So, what do I have to fix/check/redo to get back up again ?

**Comment by surfrod** [comment]
Meteor decode error:
INFO : Starting rtl_fm record
/usr/local/bin/rtl_fm: option requires an argument -- 'g'
rtl_fm, a simple narrow band FM demodulator for RTL2832 based DVB-T receivers

Use:	rtl_fm -f freq [-options] [filename]
	-f frequency_to_tune_to [Hz]
	    use multiple -f for scanning (requires squelch)
	    ranges supported, -f 118M:137M:25k
	[-M modulation (default: fm)]
	    fm, wbfm, raw, am, usb, lsb
	    wbfm == -M fm -s 170k -o 4 -A fast -r 32k -l 0 -E deemp
	    raw mode outputs 2x16 bit IQ pairs
	[-s sample_rate (default: 24k)]

**Comment by surfrod** [comment]
another error:
INFO : Bulding pass map
wxmap: error: /home/pi/raspberry-noaa/receive.sh: line 45:  6284 Segmentation fa
ult      /usr/local/bin/wxmap -T "${1}" -H "${4}" -p 0 -l 0 -o "${PASS_START}" "
${NOAA_HOME}/map/${3}-map.png"
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOA
A1820210104-214101-map.png'
Satellite: other
Status: signal processing...
wxtoimg: warning: enhancement ignored (ZA) because satellite is not NOAA or GOES
INFO : Decoding image
wxtoimg: error: could not open overlay map file '/home/pi/raspberry-noaa/map/NOA
A1820210104-214101

**Comment by surfrod** [comment]
btw I'm running on a pi4

disk partitions:
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        63G  8.7G   52G  15% /
devtmpfs        2.0G     0  2.0G   0% /dev
tmpfs           2.1G  4.1k  2.1G   1% /dev/shm
tmpfs           2.1G  9.0M  2.0G   1% /run
tmpfs           5.3M  4.1k  5.3M   1% /run/lock
tmpfs           2.1G     0  2.1G   0% /sys/fs/cgroup
tmpfs           1.1G     0  1.1G   0% /var/ramfs
/dev/mmcblk0p1  265M   56M  209M  22% /boot
tmpfs           402M  4.1k  402M   1% /run/user/1000

**Comment by surfrod** [comment]
ok, searched for "GAIN" in the issues and realized that ./install.sh did not overwrite $HOME/.noaa.conf

Just copied that and will see what happens the next pass(es)!

**Comment by reynico** [comment]
hi!

> wxtoimg: error: out of memory in line 1412 of noaa.c

This is an annoying error, got it a few times but I think it's not related to anything about the hardware, just a bug in xwxtoimg. and since we don't have the source code it's pretty tricky to find out what's going on inside.

> ok, searched for "GAIN" in the issues and realized that ./install.sh did not overwrite $HOME/.noaa.conf


good to hear! I'm including migrations for new improvements so users don't hit the wall with misconfigs

**Comment by Piccar** [comment]
> 
> 
> Thanks! I am getting accurate passes now, which I hope will result in pictures finally!
> Just one more thing, sometimes when the scheduler is run I get
> date: invalid date ‘@’
> date: invalid date ‘@’
> date: invalid date ‘@’
> date: invalid date ‘@’
> 
> So when crontab is run and the error occurs there are no passes for the day.

Noticed that this only happens to me when my raspi has no Internet connection.

**Comment by reynico** [comment]
Hi @Piccar !

Mmm, that seems to be done because of the TLE file overwrite on `schedule.sh`.


Comment out or delete those lines on `schedule.sh`
```
wget -qr http://www.celestrak.com/NORAD/elements/weather.txt -O "${NOAA_HOME}"/predict/weather.txt
wget -qr http://www.celestrak.com/NORAD/elements/amateur.txt -O "${NOAA_HOME}"/predict/amateur.txt
```

then, with an internet connection available:

```
cd /home/pi/raspberry/noaa/predict/
wget -qr http://www.celestrak.com/NORAD/elements/weather.txt
wget -qr http://www.celestrak.com/NORAD/elements/amateur.txt
```

**Comment by Anjum9694** [comment]
>wget -qr http://www.celestrak.com/NORAD/elements/weather.txt -O "${NOAA_HOME}"/predict/weather.txt
>wget -qr http://www.celestrak.com/NORAD/elements/amateur.txt -O "${NOAA_HOME}"/predict/amateur.txt

Maybe you can have schedule.sh grab the new TLE after a quick ping test for internet connection? If no connection use existing TLE files.

**Comment by Anjum9694** [comment]
Reinstalled this now on a fresh Pi installation and since I'm technically getting images now you may close this issue.
I wrote this on schedule.sh so the process doesn't stop if the internet is down.

```
if [[ "$(ping -c 1 8.8.8.8 | grep '100% packet loss' )" != "" ]]; then
    echo "INTERNET IS DOWN, SKIPPING TLE UPDATE"
else
    echo "INTERNET IS UP, UPDATING TLE"
	wget -qr http://www.celestrak.com/NORAD/elements/weather.txt -O "${NOAA_HOME}"/predict/weather.txt
	wget -qr http://www.celestrak.com/NORAD/elements/amateur.txt -O "${NOAA_HOME}"/predict/amateur.txt
fi
```

**Comment by Anjum9694** [comment]
> > Thanks! I am getting accurate passes now, which I hope will result in pictures finally!
> > Just one more thing, sometimes when the scheduler is run I get
> > date: invalid date ‘@’
> > date: invalid date ‘@’
> > date: invalid date ‘@’
> > date: invalid date ‘@’
> > So when crontab is run and the error occurs there are no passes for the day.
> 
> Noticed that this only happens to me when my raspi has no Internet connection.

The reason this happens is because wget writes an empty file when it fails to download the tle file, so the predictor software gets confused. I commented out the tle update part of the scheduler.sh and wrote my own separate 100% failproof script for the job. It makes sure the downloaded tle file has the right size before stopping. I am closing this thread as there is no problem now.

```

#!/bin/sh
#crontab -e timeout 15 bash /home/pi/raspberry-noaa/TLEupdater.sh

cd /home/pi/raspberry-noaa/predict/
curl --fail http://www.celestrak.com/NORAD/elements/weather.txt -o /home/pi/raspberry-noaa/predict/weather.txt
curl --fail http://www.celestrak.com/NORAD/elements/amateur.txt -o /home/pi/raspberry-noaa/predict/amateur.txt
#weathersize=`curl -sI http://www.celestrak.com/NORAD/elements/weather.txt | grep -i Content-Length | awk '{print $2}'`
weatherfile=`stat -c '%s' /home/pi/raspberry-noaa/predict/weather.txt`

####LOOP UNTIL THE FILE SIZE MATCHES
until ( [ "$weatherfile" \> 0 ] ); do
    curl --fail http://www.celestrak.com/NORAD/elements/weather.txt -o /home/pi/raspberry-noaa/predict/weather.txt
    weatherfile=`stat -c '%s' /home/pi/raspberry-noaa/predict/weather.txt`
done

#until [[ "$(stat -c '%s' /home/pi/raspberry-noaa/predict/amateur.txt | grep '13776' )" != "" ]]; do
#    curl --fail http://www.celestrak.com/NORAD/elements/amateur.txt -o /home/pi/raspberry-noaa/predict/amateur.txt
#done
#############################
echo TLE HAS BEEN UPDATED.


```
