### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by lben05** [reynico/raspberry-noaa#88]
Is any form fix the the permission?

**Comment by reynico** [comment]
hi! Please try

```
sudo chown pi:pi /var/www/wx/
sudo chown -R pi:pi /var/www/wx/
```

and let me know.

**Comment by lben05** [comment]
Thanks reynico realized you just describe the permission issue in one of
your post
You did a great job

**Comment by reynico** [comment]
Thank you!
