### ISSUE TITLE
Medit

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#89]
Nico,

Did You start with writing about commands for medet?
Tom

**Comment by reynico** [comment]
Hi! I did not, are you facing any problem with medet?

**Comment by tomamdy** [comment]
No problem Yet, but a week ago You said that is was very difficult to find command. I would try to colorize the Meteor pictures.

Tom

**Comment by reynico** [comment]
Could you please point me to the issue where we discussed that? I don’t recall sorry

**Comment by tomamdy** [comment]
That was:  issue: Thinking about te software. #81
One of the parts in this issue.

Tom

**Comment by reynico** [comment]
Ah, sorry.

You may want to contact artlav then: https://github.com/artlav/meteor_decoder

**Comment by tomamdy** [comment]
Out off topic.
Thank You. Nice Chrismass and I hope for all a Happy 2021
