### ISSUE TITLE
Why chandged 6 days aogo.

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#93]
Changed -g 50 to -g $GAIN  . What for a improvement is that? Because I have to change noaa.conf. too.

receive.sh
Changed -g 50 to -g $GAIN
6 days ago
receive_iss.sh
Changed -g 50 to -g $GAIN
6 days ago
receive_meteor.sh

**Comment by reynico** [comment]
Hi tom, sorry about that. I need to set some migration script for each improvement.
Run this line to setup the gain in the config file:

```
echo "GAIN=50" >> /home/pi/.noaa.conf
```

receive/receive_iss and receive_meteor scripts should remain with `$GAIN`. That way the rtl_fm gain setting is shared across the global configuration file
