### ISSUE TITLE
Raspi mail pi

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#94]
Is there a possebility to send pi mail tot a my home computer by internet ?

**Comment by pineapplee85** [comment]
You mean something like being able to remote in over FTP to view the log? That's what I do

**Comment by tomamdy** [comment]
I do that with VNCen Filezila, but I thought direct sending by e-mail.

**Comment by reynico** [comment]
Hi Tom,
Yeah I think you can use a SMTP server such as gmail or hotmail (hotmail may be easier to setup I guess)
