### ISSUE TITLE
Which Raspberry PI[ are You using ?

### ISSUE THREAD

**Issue by tomamdy** [reynico/raspberry-noaa#95]
Reynico, which Raspberry Pi type are You using yet ?

Tom

**Comment by reynico** [comment]
Hi,
Right now I'm on a Raspberry PI 4

**Comment by tegwilym** [comment]
Pi 3 on mine with RTL-SDR.

**Comment by tomamdy** [comment]
How much memory?

**Comment by reynico** [comment]
4GB

**Comment by tomamdy** [comment]
Could there be a relation between the quality of the Meteor pics and the kind of Raspberry used?

**Comment by reynico** [comment]
I haven't noticed that, it's just a matter of how much time it takes to decode a picture
